@startuml name
start
:Instalar el Juego;
if (Jugar el Tutorial) then
    :Tutorial;
endif
#Green: PanelPrincipal; 

@enduml

@startuml name1
skinparam ArrowHeadColor none
#Green :PanelPrincipal; 
note right
    Este es el entorno principal del juego
end note 
split
#Gray :Tienda;
detach
split again
#Gray :Cartas;
detach 
split again       
#Gray :Batalla;
:Jugar;
note right
  Aqui entra en el modo juego 
  ====
  salir de la partida o continuar  
end note
if (continuar) then(si)
    #Green: PanelPrincipal;
    detach
else (no)
    end 
endif

split again    
#Gray :Social;
detach 
split again
#Gray :Eventos;
detach 
end split
@enduml

@startuml
#Green :PanelPrincipal;
#Gray :Tienda;
if (entrar en la tienda) then (si)
    #Blue :TIENDA;
else (no)
    
endif 
#Green :PanelPrincipal;  
@enduml

@startuml
#Green :PanelPrincipal;
#Gray :Cartas;
if (Adquirir/Administrar cartas) then (si)
    #Blue :Admiinsitrador de Cartas ;
else (no)
    
endif 
#Green :PanelPrincipal;  
@enduml